apiVersion: v1
kind: Service
metadata:
  name: bfe
  namespace: bfe-system
  labels:
    app: bfe
spec:
  type: ClusterIP
  selector:
    app: bfe
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: monitor
    port: 8421
    targetPort: 8421
    protocol: TCP
